server:
  context-path: "/pokedex/v1"
  port: 8085
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/pokedex"
    username: postgres
    password: jaina
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true